outte:
  adapter:           mysql2
  encoding:          utf8mb4
  charset:           utf8mb4
  collation:         utf8mb4_unicode_ci
  database:          inne
  host:              localhost
  username:          root
  password:          root
  pool:              50
  timeout:           5000 # Time in milliseconds to obtain a db conn
  wait_timeout:      60   # Time in seconds to disconnect stale db conns
  idle_timeout:      60   # Time in seconds to close stale db conns (reaper)
  reaping_frequency: 60   # Time in seconds to run the db conn reaper
  reconnect:         true