outte:
  adapter:           mysql2
  encoding:          utf8mb4
  charset:           utf8mb4
  collation:         utf8mb4_unicode_ci
  database:          inne
  host:              localhost
  username:          root
  password:          root
  pool:              100    # Connection pool size
  timeout:           5000   # Time in milliseconds to obtain a db conn (deprecated?)
  checkout_timeout:  60     # Time in seconds to obtain a db connection
  wait_timeout:      60     # Time in seconds to close idle connections (MySQL)
  idle_timeout:      60     # Time in seconds to close idle connections (Rails pool)
  reaping_frequency: 60     # Time in seconds to run the db conn reaper
#  reconnect:         true